# Generated by Django 4.2.1 on 2025-05-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worddetail",
            name="word",
            field=models.CharField(db_index=True, max_length=100, verbose_name="Word"),
        ),
        migrations.AlterUniqueTogether(
            name="worddetail",
            unique_together={("lang_code", "word")},
        ),
    ]
