# Generated by Django 4.2.1 on 2025-05-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("words", "0002_alter_worddetail_word_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worddetail",
            name="lemma_morph",
            field=models.CharField(
                default=None, max_length=150, null=True, verbose_name="Lemma Morphology"
            ),
        ),
    ]
