export const LANGUAGE_TO_CODES_WIKTIONARY = new Map<string, string>([
  ["English", "en"],
  ["French", "fr"],
  ["Malagasy", "mg"],
  ["Chinese", "zh"],
  ["Greek", "el"],
  ["Thai", "th"],
  ["Russian", "ru"],
  ["German", "de"],
  ["Kurdish", "ku"],
  ["Swedish", "sv"],
  ["Dutch", "nl"],
  ["Spanish", "es"],
  ["Serbo-Croatian", "sh"],
  ["Polish", "pl"],
  ["Lithuanian", "lt"],
  ["Catalan", "ca"],
  ["Finnish", "fi"],
  ["Italian", "it"],
  ["Hungarian", "hu"],
  ["Portuguese", "pt"],
  ["Japanese", "ja"],
  ["Tamil", "ta"],
  ["Turkish", "tr"],
  ["Ido", "io"],
  ["Armenian", "hy"],
  ["Korean", "ko"],
  ["Vietnamese", "vi"],
  ["Kannada", "kn"],
  ["Serbian", "sr"],
  ["Hindi", "hi"],
  ["Indonesian", "id"],
  ["Romanian", "ro"],
  ["Estonian", "et"],
  ["Norwegian", "no"],
  ["Czech", "cs"],
  ["Saraiki", "skr"],
  ["Malayalam", "ml"],
  ["Burmese", "my"],
  ["Limburgish", "li"],
  ["Uzbek", "uz"],
  ["Esperanto", "eo"],
  ["Odia", "or"],
  ["Persian", "fa"],
  ["Telugu", "te"],
  ["Bangla", "bn"],
  ["Icelandic", "is"],
  ["Sango", "sg"],
  ["Galician", "gl"],
  ["Occitan", "oc"],
  ["Asturian", "ast"],
  ["Arabic", "ar"],
  ["Javanese", "jv"],
  ["Mon", "mnw"],
  ["Malay", "ms"],
  ["Ukrainian", "uk"],
  ["Azerbaijani", "az"],
  ["Basque", "eu"],
  ["Breton", "br"],
  ["Simple English", "simple"],
  ["Danish", "da"],
  ["Shan", "shn"],
  ["Kabardian", "kbd"],
  ["Slovak", "sk"],
  ["Latin", "la"],
  ["Lombard", "lmo"],
  ["Walloon", "wa"],
  ["Kyrgyz", "ky"],
  ["Croatian", "hr"],
  ["Fijian", "fj"],
  ["Bulgarian", "bg"],
  ["Lao", "lo"],
  ["Welsh", "cy"],
  ["Urdu", "ur"],
  ["Tajik", "tg"],
  ["Pashto", "ps"],
  ["Hebrew", "he"],
  ["Volapük", "vo"],
  ["Afrikaans", "af"],
  ["Oromo", "om"],
  ["Slovenian", "sl"],
  ["Minnan", "zh-min-nan"],
  ["Georgian", "ka"],
  ["Sicilian", "scn"],
  ["Tagalog", "tl"],
  ["Swahili", "sw"],
  ["Western Frisian", "fy"],
  ["Kazakh", "kk"],
  ["Minangkabau", "min"],
  ["Gorontalo", "gor"],
  ["Norwegian Nynorsk", "nn"],
  ["Latvian", "lv"],
  ["Luxembourgish", "lb"],
  ["Albanian", "sq"],
  ["Low German", "nds"],
  ["Mongolian", "mn"],
  ["Corsican", "co"],
  ["Western Punjabi", "pnb"],
  ["Dimli", "diq"],
  ["Central Kurdish", "ckb"],
  ["Cantonese", "zh-yue"],
  ["Nahuatl", "nah"],
  ["Madurese", "mad"],
  ["Khmer", "km"],
  ["Sanskrit", "sa"],
  ["Nias", "nia"],
  ["Sinhala", "si"],
  ["Belarusian", "be"],
  ["Macedonian", "mk"],
  ["Venetian", "vec"],
  ["Turkmen", "tk"],
  ["Banjar", "bjn"],
  ["Samoan", "sm"],
  ["Central Bikol", "bcl"],
  ["Upper Sorbian", "hsb"],
  ["Kara-Kalpak", "kaa"],
  ["Batak Mandailing", "btm"],
  ["Hausa", "ha"],
  ["Kashmiri", "ks"],
  ["Somali", "so"],
  ["Shawiya", "shy"],
  ["Punjabi", "pa"],
  ["Irish", "ga"],
  ["Sundanese", "su"],
  ["Scottish Gaelic", "gd"],
  ["Aragonese", "an"],
  ["Goan Konkani", "gom"],
  ["Pa'O", "blk"],
  ["Marathi", "mr"],
  ["Wolof", "wo"],
  ["Manipuri", "mni"],
  ["Interlingua", "ia"],
  ["Maltese", "mt"],
  ["Sindhi", "sd"],
  ["Tatar", "tt"],
  ["Faroese", "fo"],
  ["Old English", "ang"],
  ["Guarani", "gn"],
  ["Māori", "mi"],
  ["Interlingue", "ie"],
  ["Kashubian", "csb"],
  ["Uyghur", "ug"],
  ["Gun", "guw"],
  ["Lojban", "jbo"],
  ["Tyap", "kcg"],
  ["Southern Sotho", "st"],
  ["Fiji Hindi", "hif"],
  ["Aromanian", "roa-rup"],
  ["Kalaallisut", "kl"],
  ["Zulu", "zu"],
  ["Tulu", "tcy"],
  ["Lingala", "ln"],
  ["Amharic", "am"],
  ["Santali", "sat"],
  ["Yiddish", "yi"],
  ["Gujarati", "gu"],
  ["Nauru", "na"],
  ["Manx", "gv"],
  ["Tok Pisin", "tpi"],
  ["Cornish", "kw"],
  ["Aymara", "ay"],
  ["Nepali", "ne"],
  ["Kinyarwanda", "rw"],
  ["Tsonga", "ts"],
  ["Quechua", "qu"],
  ["Igbo", "ig"],
  ["Inuktitut", "iu"],
  ["Swati", "ss"],
  ["Cherokee", "chr"],
  ["Divehi", "dv"],
  ["Tigrinya", "ti"],
  ["Tswana", "tn"],
  ["Bosnian", "bs"],
]);

const LANGUAGE_TO_CODES_GOOGLE_TRANS_API = [
  // Note that the native language was populated by an llm and may not be correct.
  ["Abkhaz", "ab", "Аҧсуа"],
  ["Acehnese", "ace", "ᨅᨕᨙᨔᨕᨘ"],
  ["Acholi", "ach", "Acholi"],
  ["Afrikaans", "af", "Afrikaans"],
  ["Albanian", "sq", "Shqip"],
  ["Alur", "alz", "Alur"],
  ["Amharic", "am", "አማርኛ"],
  ["Arabic", "ar", "العربية"],
  ["Armenian", "hy", "Հայերեն"],
  ["Assamese", "as", "অসমীয়া"],
  ["Awadhi", "awa", "अवधी"],
  ["Aymara", "ay", "Aymara"],
  ["Azerbaijani", "az", "Azərbaycan dili"],
  ["Balinese", "ban", "ᬩᬮᬶᬦᬶᬱᬶ"],
  ["Bambara", "bm", "Bamanankan"],
  ["Bashkir", "ba", "Башҡорт теле"],
  ["Basque", "eu", "Euskara"],
  ["Batak Karo", "btx", "ᯅᯧᯔᯧᯍᯧᯔᯧ"],
  ["Batak Simalungun", "bts", "ᯅᯧᯔᯧᯍᯧᯔᯧᯀᯧᯔᯧᯍᯧᯔᯧ"],
  ["Batak Toba", "bbc", "ᯅᯧᯔᯧᯍᯧᯔᯧᯆᯧᯔᯧᯍᯧᯔᯧ"],
  ["Belarusian", "be", "Беларуская мова"],
  ["Bemba", "bem", "Bemba"],
  ["Bengali", "bn", "বাংলা"],
  ["Betawi", "bew", "Betawi"],
  ["Bhojpuri", "bho", "भोजपुरी"],
  ["Bikol", "bik", "Bikol"],
  ["Bosnian", "bs", "Bosanski"],
  ["Breton", "br", "Brezhoneg"],
  ["Bulgarian", "bg", "Български"],
  ["Buryat", "bua", "Буряад хэлэн"],
  ["Cantonese", "yue", "粵語"],
  ["Catalan", "ca", "Català"],
  ["Cebuano", "ceb", "Cebuano"],
  ["Chichewa (Nyanja)", "ny", "Chichewa"],
  ["Chinese (Simplified)", " -CN", "简体中文"],
  ["Chinese (Traditional)", "zh-TW", "繁體中文"],
  ["Chuvash", "cv", "Чӑваш чӗлхи"],
  ["Corsican", "co", "Corsu"],
  ["Crimean Tatar", "crh", "Qırımtatarca"],
  ["Croatian", "hr", "Hrvatski"],
  ["Czech", "cs", "Čeština"],
  ["Danish", "da", "Dansk"],
  ["Dinka", "din", "Thuɔŋjäŋ"],
  ["Divehi", "dv", "ދިވެހި"],
  ["Dogri", "doi", "डोगरी"],
  ["Dombe", "dov", "Dɔmbe"],
  ["Dutch", "nl", "Nederlands"],
  ["Dzongkha", "dz", "རྫོང་ཁ"],
  ["English", "en", "English"],
  ["Esperanto", "eo", "Esperanto"],
  ["Estonian", "et", "Eesti keel"],
  ["Ewe", "ee", "Eʋegbe"],
  ["Fijian", "fj", "Na Vosa Vakaviti"],
  ["Filipino (Tagalog)", "fil", "Filipino"],
  ["Finnish", "fi", "Suomi"],
  ["French", "fr", "Français"],
  ["French (Canadian)", "fr-CA", "Français (Canada)"],
  ["Frisian", "fy", "Frysk"],
  ["Fulfulde", "ff", "Fulfulde"],
  ["Ga", "gaa", "Ga"],
  ["Galician", "gl", "Galego"],
  ["Ganda (Luganda)", "lg", "Luganda"],
  ["Georgian", "ka", "ქართული"],
  ["German", "de", "Deutsch"],
  ["Greek", "el", "Ελληνικά"],
  ["Guarani", "gn", "Añañe'ẽ"],
  ["Gujarati", "gu", "ગુજરાતી"],
  ["Haitian Creole", "ht", "Kreyòl Ayisyen"],
  ["Hakha Chin", "cnh", "Laiholh"],
  ["Hausa", "ha", "هَوُسَ"],
  ["Hawaiian", "haw", "ʻŌlelo Hawaiʻi"],
  ["Hebrew", "iw", "עברית"],
  ["Hiligaynon", "hil", "Ilonggo"],
  ["Hindi", "hi", "हिन्दी"],
  ["Hmong", "hmn", "Hmoob"],
  ["Hungarian", "hu", "Magyar"],
  ["Icelandic", "is", "Íslenska"],
  ["Igbo", "ig", "Igbo"],
  ["Iloko", "ilo", "Ilokano"],
  ["Indonesian", "id", "Bahasa Indonesia"],
  ["Irish", "ga", "Gaeilge"],
  ["Italian", "it", "Italiano"],
  ["Japanese", "ja", "日本語"],
  ["Javanese", "jw", "ꦧꦱꦗꦮ"],
  ["Kannada", "kn", "ಕನ್ನಡ"],
  ["Kazakh", "kk", "Қазақ тілі"],
  ["Khmer", "km", "ភាសាខ្មែរ"],
  ["Kinyarwanda", "rw", "Ikinyarwanda"],
  ["Korean", "ko", "한국어"],
  ["Kurdish (Kurmanji)", "ku", "Kurdî"],
  ["Kurdish (Sorani)", "ckb", "کوردی"],
  ["Kyrgyz", "ky", "Кыргыз тили"],
  ["Lao", "lo", "ລາວ"],
  ["Latvian", "lv", "Latviešu valoda"],
  ["Lithuanian", "lt", "Lietuvių kalba"],
  ["Luxembourgish", "lb", "Lëtzebuergesch"],
  ["Macedonian", "mk", "Македонски"],
  ["Maithili", "mai", "मैथिली"],
  ["Maltese", "mt", "Il-L-Ilsien Malti"],
  ["Marathi", "mr", "मराठी"],
  ["Mongolian", "mn", "Монгол хэл"],
  ["Nepali", "ne", "नेपाली"],
  ["Norwegian", "no", "Norsk"],
  ["Odia (Oriya)", "or", "ଓଡ଼ିଆ"],
  ["Pashto", "ps", "پښتو"],
  ["Persian", "fa", "فارسی"],
  ["Polish", "pl", "Polski"],
  ["Portuguese", "pt", "Português"],
  ["Punjabi", "pa", "ਪੰਜਾਬੀ"],
  ["Quechua", "qu", "Runa Simi"],
  ["Romanian", "ro", "Română"],
  ["Russian", "ru", "Русский"],
  ["Serbian", "sr", "Српски"],
  ["Sinhala (Sinhalese)", "si", "සිංහල"],
  ["Slovak", "sk", "Slovenčina"],
  ["Slovenian", "sl", "Slovenščina"],
  ["Somali", "so", "Soomaali"],
  ["Spanish", "es", "Español"],
  ["Swahili", "sw", "Kiswahili"],
  ["Swedish", "sv", "Svenska"],
  ["Tajik", "tg", "Тоҷикӣ"],
  ["Tamil", "ta", "தமிழ்"],
  ["Telugu", "te", "తెలుగు"],
  ["Thai", "th", "ไทย"],
  ["Tigrinya", "ti", "ትግርኛ"],
  ["Turkish", "tr", "Türkçe"],
  ["Ukrainian", "uk", "Українська"],
  ["Urdu", "ur", "اردو"],
  ["Uzbek", "uz", "Oʻzbek tili"],
  ["Vietnamese", "vi", "Tiếng Việt"],
  ["Welsh", "cy", "Cymraeg"],
  ["Xhosa", "xh", "isiXhosa"],
  ["Yiddish", "yi", "ייִדיש"],
  ["Yoruba", "yo", "Yorùbá"],
  ["Zulu", "zu", "isiZulu"],
];
interface GoogleLanguageDetails {
  en_name: string;
  native_lang: string;
}

type GoogleLanguageEntry = { [code: string]: GoogleLanguageDetails };

export const GOOGLE_LANG_OBJ: GoogleLanguageEntry[] = [
  { ab: { en_name: "Abkhaz", native_lang: "Аҧсуа" } },
  { ace: { en_name: "Acehnese", native_lang: "ᨅᨕᨙᨔᨕᨘ" } },
  { ach: { en_name: "Acholi", native_lang: "Acholi" } },
  { af: { en_name: "Afrikaans", native_lang: "Afrikaans" } },
  { sq: { en_name: "Albanian", native_lang: "Shqip" } },
  { alz: { en_name: "Alur", native_lang: "Alur" } },
  { am: { en_name: "Amharic", native_lang: "አማርኛ" } },
  { ar: { en_name: "Arabic", native_lang: "العربية" } },
  { hy: { en_name: "Armenian", native_lang: "Հայերեն" } },
  { as: { en_name: "Assamese", native_lang: "অসমীয়া" } },
  { awa: { en_name: "Awadhi", native_lang: "अवधी" } },
  { ay: { en_name: "Aymara", native_lang: "Aymara" } },
  { az: { en_name: "Azerbaijani", native_lang: "Azərbaycan dili" } },
  { ban: { en_name: "Balinese", native_lang: "ᬩᬮᬶᬦᬶᬱᬶ" } },
  { bm: { en_name: "Bambara", native_lang: "Bamanankan" } },
  { ba: { en_name: "Bashkir", native_lang: "Башҡорт теле" } },
  { eu: { en_name: "Basque", native_lang: "Euskara" } },
  { btx: { en_name: "Batak Karo", native_lang: "ᯅᯧᯔᯧᯍᯧᯔᯧ" } },
  { bts: { en_name: "Batak Simalungun", native_lang: "ᯅᯧᯔᯧᯍᯧᯔᯧᯀᯧᯔᯧᯍᯧᯔᯧ" } },
  { bbc: { en_name: "Batak Toba", native_lang: "ᯅᯧᯔᯧᯍᯧᯔᯧᯆᯧᯔᯧᯍᯧᯔᯧ" } },
  { be: { en_name: "Belarusian", native_lang: "Беларуская мова" } },
  { bem: { en_name: "Bemba", native_lang: "Bemba" } },
  { bn: { en_name: "Bengali", native_lang: "বাংলা" } },
  { bew: { en_name: "Betawi", native_lang: "Betawi" } },
  { bho: { en_name: "Bhojpuri", native_lang: "भोजपुरी" } },
  { bik: { en_name: "Bikol", native_lang: "Bikol" } },
  { bs: { en_name: "Bosnian", native_lang: "Bosanski" } },
  { br: { en_name: "Breton", native_lang: "Brezhoneg" } },
  { bg: { en_name: "Bulgarian", native_lang: "Български" } },
  { bua: { en_name: "Buryat", native_lang: "Буряад хэлэн" } },
  { yue: { en_name: "Cantonese", native_lang: "粵語" } },
  { ca: { en_name: "Catalan", native_lang: "Català" } },
  { ceb: { en_name: "Cebuano", native_lang: "Cebuano" } },
  { ny: { en_name: "Chichewa (Nyanja)", native_lang: "Chichewa" } },
  { "zh-CN": { en_name: "Chinese (Simplified)", native_lang: "简体中文" } },
  { "zh-TW": { en_name: "Chinese (Traditional)", native_lang: "繁體中文" } },
  { cv: { en_name: "Chuvash", native_lang: "Чӑваш чӗлхи" } },
  { co: { en_name: "Corsican", native_lang: "Corsu" } },
  { crh: { en_name: "Crimean Tatar", native_lang: "Qırımtatarca" } },
  { hr: { en_name: "Croatian", native_lang: "Hrvatski" } },
  { cs: { en_name: "Czech", native_lang: "Čeština" } },
  { da: { en_name: "Danish", native_lang: "Dansk" } },
  { din: { en_name: "Dinka", native_lang: "Thuɔŋjäŋ" } },
  { dv: { en_name: "Divehi", native_lang: "ދިވެހި" } },
  { doi: { en_name: "Dogri", native_lang: "डोगरी" } },
  { dov: { en_name: "Dombe", native_lang: "Dɔmbe" } },
  { nl: { en_name: "Dutch", native_lang: "Nederlands" } },
  { dz: { en_name: "Dzongkha", native_lang: "རྫོང་ཁ" } },
  { en: { en_name: "English", native_lang: "English" } },
  { eo: { en_name: "Esperanto", native_lang: "Esperanto" } },
  { et: { en_name: "Estonian", native_lang: "Eesti keel" } },
  { ee: { en_name: "Ewe", native_lang: "Eʋegbe" } },
  { fj: { en_name: "Fijian", native_lang: "Na Vosa Vakaviti" } },
  { fil: { en_name: "Filipino (Tagalog)", native_lang: "Filipino" } },
  { fi: { en_name: "Finnish", native_lang: "Suomi" } },
  { fr: { en_name: "French", native_lang: "Français" } },
  {
    "fr-CA": { en_name: "French (Canadian)", native_lang: "Français (Canada)" },
  },
  { fy: { en_name: "Frisian", native_lang: "Frysk" } },
  { ff: { en_name: "Fulfulde", native_lang: "Fulfulde" } },
  { gaa: { en_name: "Ga", native_lang: "Ga" } },
  { gl: { en_name: "Galician", native_lang: "Galego" } },
  { lg: { en_name: "Ganda (Luganda)", native_lang: "Luganda" } },
  { ka: { en_name: "Georgian", native_lang: "ქართული" } },
  { de: { en_name: "German", native_lang: "Deutsch" } },
  { el: { en_name: "Greek", native_lang: "Ελληνικά" } },
  { gn: { en_name: "Guarani", native_lang: "Añañe'ẽ" } },
  { gu: { en_name: "Gujarati", native_lang: "ગુજરાતી" } },
  { ht: { en_name: "Haitian Creole", native_lang: "Kreyòl Ayisyen" } },
  { cnh: { en_name: "Hakha Chin", native_lang: "Laiholh" } },
  { ha: { en_name: "Hausa", native_lang: "هَوُسَ" } },
  { haw: { en_name: "Hawaiian", native_lang: "ʻŌlelo Hawaiʻi" } },
  { iw: { en_name: "Hebrew", native_lang: "עברית" } },
  { hil: { en_name: "Hiligaynon", native_lang: "Ilonggo" } },
  { hi: { en_name: "Hindi", native_lang: "हिन्दी" } },
  { hmn: { en_name: "Hmong", native_lang: "Hmoob" } },
  { hu: { en_name: "Hungarian", native_lang: "Magyar" } },
  { is: { en_name: "Icelandic", native_lang: "Íslenska" } },
  { ig: { en_name: "Igbo", native_lang: "Igbo" } },
  { ilo: { en_name: "Iloko", native_lang: "Ilokano" } },
  { id: { en_name: "Indonesian", native_lang: "Bahasa Indonesia" } },
  { ga: { en_name: "Irish", native_lang: "Gaeilge" } },
  { it: { en_name: "Italian", native_lang: "Italiano" } },
  { ja: { en_name: "Japanese", native_lang: "日本語" } },
  { jw: { en_name: "Javanese", native_lang: "ꦧꦱꦗꦮ" } },
  { kn: { en_name: "Kannada", native_lang: "ಕನ್ನಡ" } },
  { kk: { en_name: "Kazakh", native_lang: "Қазақ тілі" } },
  { km: { en_name: "Khmer", native_lang: "ភាសាខ្មែរ" } },
  { rw: { en_name: "Kinyarwanda", native_lang: "Ikinyarwanda" } },
  { ko: { en_name: "Korean", native_lang: "한국어" } },
  { ku: { en_name: "Kurdish (Kurmanji)", native_lang: "Kurdî" } },
  { ckb: { en_name: "Kurdish (Sorani)", native_lang: "کوردی" } },
  { ky: { en_name: "Kyrgyz", native_lang: "Кыргыз тили" } },
  { lo: { en_name: "Lao", native_lang: "ລາວ" } },
  { lv: { en_name: "Latvian", native_lang: "Latviešu valoda" } },
  { lt: { en_name: "Lithuanian", native_lang: "Lietuvių kalba" } },
  { lb: { en_name: "Luxembourgish", native_lang: "Lëtzebuergesch" } },
  { mk: { en_name: "Macedonian", native_lang: "Македонски" } },
  { mai: { en_name: "Maithili", native_lang: "मैथिली" } },
  { mt: { en_name: "Maltese", native_lang: "Il-L-Ilsien Malti" } },
  { mr: { en_name: "Marathi", native_lang: "मराठी" } },
  { mn: { en_name: "Mongolian", native_lang: "Монгол хэл" } },
  { ne: { en_name: "Nepali", native_lang: "नेपाली" } },
  { no: { en_name: "Norwegian", native_lang: "Norsk" } },
  { or: { en_name: "Odia (Oriya)", native_lang: "ଓଡ଼ିଆ" } },
  { ps: { en_name: "Pashto", native_lang: "پښتو" } },
  { fa: { en_name: "Persian", native_lang: "فارسی" } },
  { pl: { en_name: "Polish", native_lang: "Polski" } },
  { pt: { en_name: "Portuguese", native_lang: "Português" } },
  { pa: { en_name: "Punjabi", native_lang: "ਪੰਜਾਬੀ" } },
  { qu: { en_name: "Quechua", native_lang: "Runa Simi" } },
  { ro: { en_name: "Romanian", native_lang: "Română" } },
  { ru: { en_name: "Russian", native_lang: "Русский" } },
  { sr: { en_name: "Serbian", native_lang: "Српски" } },
  { si: { en_name: "Sinhala (Sinhalese)", native_lang: "සිංහල" } },
  { sk: { en_name: "Slovak", native_lang: "Slovenčina" } },
  { sl: { en_name: "Slovenian", native_lang: "Slovenščina" } },
  { so: { en_name: "Somali", native_lang: "Soomaali" } },
  { es: { en_name: "Spanish", native_lang: "Español" } },
  { sw: { en_name: "Swahili", native_lang: "Kiswahili" } },
  { sv: { en_name: "Swedish", native_lang: "Svenska" } },
  { tg: { en_name: "Tajik", native_lang: "Тоҷикӣ" } },
  { ta: { en_name: "Tamil", native_lang: "தமிழ்" } },
  { te: { en_name: "Telugu", native_lang: "తెలుగు" } },
  { th: { en_name: "Thai", native_lang: "ไทย" } },
  { ti: { en_name: "Tigrinya", native_lang: "ትግርኛ" } },
  { tr: { en_name: "Turkish", native_lang: "Türkçe" } },
  { uk: { en_name: "Ukrainian", native_lang: "Українська" } },
  { ur: { en_name: "Urdu", native_lang: "اردو" } },
  { uz: { en_name: "Uzbek", native_lang: "Oʻzbek tili" } },
  { vi: { en_name: "Vietnamese", native_lang: "Tiếng Việt" } },
  { cy: { en_name: "Welsh", native_lang: "Cymraeg" } },
  { xh: { en_name: "Xhosa", native_lang: "isiXhosa" } },
  { yi: { en_name: "Yiddish", native_lang: "ייִדיש" } },
  { yo: { en_name: "Yoruba", native_lang: "Yorùbá" } },
  { zu: { en_name: "Zulu", native_lang: "isiZulu" } },
];
