# Generated by Django 4.2.1 on 2023-06-04 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="native_language",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="spanish_fluency",
        ),
    ]
