# Generated by Django 4.2.1 on 2024-03-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_profile_native_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="/profile_default.svg",
                upload_to="",
                verbose_name="Profile Photo",
            ),
        ),
    ]
